### ISSUE TITLE
Allow selection of non-leaf nodes in TreeCheckable mode

### ISSUE THREAD

**Issue by diegokogan** [react-component/tree-select#10]
In the "check select" example (at http://react-component.github.io/tree-select/examples/basic.html) , sometimes is useful to not only to select the leaf nodes, but also the parent's.
![snap31](https://cloud.githubusercontent.com/assets/468985/13647952/2e81ca02-e615-11e5-81c5-44adca356f4f.png)
For instance, in this example, it should select (maybe with an extra property to allow this mode) not only the already selected nodes, but also the node: 0-0-0-label

As a workaround we simply commented this line at Select.jsx
`checkedNodes = checkedNodes.filter(n => !n.props.children);`

**Comment by warmhug** [comment]
It's not so easy. Because thus you deselect non-leaf nodes from Input panel, it's children nodes need to deselect also... 
Anyway, i will consider it.

**Comment by yiminghe** [comment]
showCheckStrategy=TreeSelect.SHOW_ALL
