### ISSUE TITLE
Option to keep popup placement from changing on resize?

### ISSUE THREAD

**Issue by adamgruber** [react-component/tree-select#12]
If dropdown is open and I resize the window to be shorter, sometimes the dropdown will be positioned above the trigger. I would like an option to ignore this behavior and keep the dropdown placement below. Is this possible?

**Comment by warmhug** [comment]
@yiminghe

**Comment by yiminghe** [comment]
dropdownPopupAlign {adjustY:1, adjustX:1}

**Comment by adamgruber** [comment]
:+1:

**Comment by johnmwai** [comment]
`dropdownPopupAlign={{overflow: { adjustY: 0, adjustX: 0 }}}`
