### ISSUE TITLE
1.5.0 has breaking changes, should be 2.0.0

### ISSUE THREAD

**Issue by adamgruber** [react-component/tree-select#13]
Changes were made to `fireChange` method in `Select.jsx` that are breaking. Previous versions would call `fireChange` with two params, the code for selected item and extra info. 1.5.0 changed this to be called only with selected item value which is now an object.

Since this is a breaking change the version should have been implemented to 2.0.0 to avoid issues.

Here's the change: https://github.com/react-component/tree-select/blob/master/src/Select.jsx#L658

**Comment by warmhug** [comment]
Thank you for your suggest. You can think it's a bug in 1.5.0, it has been fixed in 1.5.2, I'm sorry for this. 
In 1.x, I will try to keep backwards compatible. Now not ready enough to upgrade major version to 2.x
