### ISSUE TITLE
showSearch for mutiple mode

### ISSUE THREAD

**Issue by ruchigoyal2005** [react-component/tree-select#15]
Is it possible to use showSearch prop in mutiple mode? I want user to allow search/filter the results in a deep hierarchy tree. 
Also, Is there any property to close the tree-input (multiple mode) dropdown once user select any item?

**Comment by warmhug** [comment]
It can search in mutiple mode default, but the search box is not display in dropdown, unlike in single select mode.

> close the tree-input (multiple mode) dropdown once user select any item

If so, may need a controlled `open` prop, thus it also should exist in `Select` component. @yiminghe

**Comment by yiminghe** [comment]
this interaction is by design,

multiple does not need search, input can be used for filter
