### ISSUE TITLE
need supports for multi-select

### ISSUE THREAD

**Issue by connorTang** [react-component/tree-select#17]
I managed it to display the arrow and clear all for multi-select mode, but when I select more, the new selected nodes will be out of the box. Can it just display 2 or 3 nodes, then follow with "...(x more nodes selected)"?

**Comment by warmhug** [comment]
you can set `max-height` and `overflow: auto`, like this:
![image](https://cloud.githubusercontent.com/assets/2011119/14975991/0f8e067e-113a-11e6-94c3-1715775c94bc.png)
http://react-component.github.io/tree-select/examples/basic.html

**Comment by connorTang** [comment]
Thanks a lot, I have solved that. One question: what do you use to compile the source code? since they all come like vanilla JS.

**Comment by warmhug** [comment]
babel and webpack

**Comment by connorTang** [comment]
I forked this repo, thinking to do some customization, but I'm struggling with the setup of webpack. Could you please post the configuration of webpack? That would save me a lot work/time. Thanks in advance.

**Comment by warmhug** [comment]
Here: https://github.com/react-component/rc-tools/tree/master/lib
![image](https://cloud.githubusercontent.com/assets/2011119/15063323/d11714e6-137b-11e6-9065-122fd1f13033.png)
