### ISSUE TITLE
the same title and value, different key

### ISSUE THREAD

**Issue by BartekMilew** [react-component/tree-select#189]
Hello,
i have a problem. I have json, around 600 values. 

[{
"children:[
"key":2,
"title":"TEST",
"value"::TEST"
]
"key":1,
"title":"TEST",
"value"::TEST"
etc....

This json has a different keys but some of values and titles, are the same. When i select one in multiple select with checked, i get this one plus some more extra beacuse it has the same titles. 

is it possible to change this. select only by the key but in selected input has a title of this value?

**Comment by dexterdeng** [comment]
Hello, @zombieJ   I need this too.

**Comment by zombieJ** [comment]
Noop. `value` of TreeNode should be unique. You can not tell apart which treeNode with same value is checked by control mode.

**Comment by laszlo-zaptic** [comment]
i need this too, to have same value in different parts of the hierarchy
