### ISSUE TITLE
Use rc-trigger 2.x as 3.0 RC is not maintained

### ISSUE THREAD

**Issue by bianjp** [react-component/tree-select#194]
[rc-trigger](https://github.com/react-component/trigger/releases) 3.0 RC is not actively maintained (the last release is Jul 3, 2018), and it has some outdated dependencies (rc-animate > fbjs > core-js@1.2.7).

It seems that the 3.0 RC has be abandoned. So please change the `rc-trigger` dependency version to 2.x.

**Comment by bianjp** [comment]
@zombieJ Could you take a look at this issue?

**Comment by zombieJ** [comment]
Thanks for feedback. antd v4 is working on the refactor. `rc-trigger` is in the plan.
We will update `rc-trigger` after Select & TreeSelect finished.
