### ISSUE TITLE
Is the tree-select going to support virtualized tree view?

### ISSUE THREAD

**Issue by connorTang** [react-component/tree-select#20]
I'm seeing [react-virtualized](https://github.com/bvaughn/react-virtualized) has an example of visualized tree view, so I'm wondering if the tree-select can take some of that advantage to make the tree view visualized? My data could be pretty large on each level, so it will be useful to make it virtualized.

**Comment by warmhug** [comment]
Very good feature! I'm doing a similar feature in [m-list-view](https://github.com/react-component/m-list-view), but have not yet to consider this in tree-select.

By the way, I've written some optimization tips [here](https://github.com/react-component/tree-select#note), 
![image](https://cloud.githubusercontent.com/assets/2011119/16145742/d28b63d4-34ac-11e6-9de6-eef83f5566b5.png)
 this tip will help you.
