### ISSUE TITLE
After search, previously selected value is lost.

### ISSUE THREAD

**Issue by connorTang** [react-component/tree-select#21]
```javascript
      <TreeSelect
        className={className.select}
        treeLine
        treeCheckable
        treeCheckStrictly
        treeNodeFilterProp="label"
        treeData={treeData}
        value={selected}
        placeholder={'Please Search'}
        onChange={onChange}
      />
```
This is my code that using the lib, and the onChange is a callback function passed in from parent, the function only calls setState for selected values. But I found that doing search will show the matched items and their parents in the dropdown menu, then if I check an item, the previously selected items (not match the search) will be lost.

**Comment by warmhug** [comment]
I can't find the issue in my demo, it works properly, see [here](http://react-component.github.io/tree-select/examples/basic.html), try it. 
![image](https://cloud.githubusercontent.com/assets/2011119/16146177/54d6c890-34af-11e6-9e87-bff976351a3d.png)

**Comment by connorTang** [comment]
I did a little research, and found that the issue happens when I use treeCheckStrictly. The issue also happens when I add treeCheckStrictly to that example code. I'm going to keep looking what cause it, but maybe you have better insight.

**Comment by warmhug** [comment]
Do you know the reason?

**Comment by warmhug** [comment]
`treeCheckStrictly` is a bit special here, and reference the [usage](http://react-component.github.io/tree-select/examples/big-data.html) of it here please.
![image](https://cloud.githubusercontent.com/assets/2011119/16198697/5cae583a-3739-11e6-89ff-789f44866211.png)

**Comment by connorTang** [comment]
I think the problem may be in the rc-tree. The scenario is searching and checking a tree node. Without treeCheckStrictly, the tree always returns an array of all selected value. But when turn on treeCheckStrictly, it only returns an array of objects which are rendered in the current tree. In other words, if the tree node has been filtered out by search, we lost the selected value for that node in the state of tree.

**Comment by connorTang** [comment]
I have a workaround for now, I add a global variable `searching` to check if we're doing search or not. Then in `onChange()`, union the current and previous selected value together. (fyi. here I introduced unionBy from lodash).

```javascript
  onSearch(value) {
    if ( value === "" || value === null ) {
      searching = false;
    } else {
      searching = true;
    }
    // console.log(value, arguments);
  },
  onChange(value) {
    if (searching) {
      console.log('onChange', arguments);
      let theValue = this.state.value;
      if ( theValue.length > 0 ) {
        theValue = unionBy( theValue, value, 'value' );
      }

      value = theValue;
      searching = false;
    }
    this.setState({ value });
  }
```

note: I think it's better if we can fix this in the lib.

**Comment by winterJIE** [comment]
这个问题我在用的时候也遇到了，看官方demo 有没有问题，props 又比较多, 看ant.design http://ant.design/components/tree-select 第三个有搜索功能的demo 完全不具有参考价值 因为第三个demo 根本没有实现搜索的实际功能，排查了很久，和 rc 的 basic demo 里的 check select 的props 一个一个对比才发现 如果要搜索 必须要传 inputValue={null} 这个props 才会在搜索之后更新数据，所以建议是不是可以考虑把 inputValue 这个props 内部处理了 而不是要让使用者传这么一个写死的 props

**Comment by winterJIE** [comment]
而且现在http://react-component.github.io/tree-select/examples/basic.html 这个demo 里的 check select 也的搜索也是有问题的 搜索之后并不能正确选中 可以尽快修复这个 bug 吗？

**Comment by yiminghe** [comment]
@warmhug

**Comment by warmhug** [comment]
try rc-tree-select@1.7.9 and demo http://react-component.github.io/tree-select/examples/filter.html

**Comment by connorTang** [comment]
closing this, as the problem has been fixed.
