### ISSUE TITLE
What's the issue of clearAll with multiple?

### ISSUE THREAD

**Issue by connorTang** [react-component/tree-select#23]
I saw this `allowClear && !multiple ? clear : null`, so I wonder why don't allow clear for multiple mode? I think check select is also considered multiple mode, that would be nice if I can use one button to clear all selection.

**Comment by warmhug** [comment]
There should be no issue about it. But we don't think we should show it. Sorry for that.

**Comment by connorTang** [comment]
Then is it possible to remove the check on multiple for clear?
