### ISSUE TITLE
Need dropdown menu positioned relative to the selection area.

### ISSUE THREAD

**Issue by connorTang** [react-component/tree-select#29]
Now it seems the dropdown menu is positioned based on how much top to the whole page, so it gives me a problem that if I use the tree-select in a model. If I can scroll in the model, the dropdown menu will remain at the position it appears, which looks like it's broken.

**Comment by warmhug** [comment]
@yiminghe

**Comment by yiminghe** [comment]
implement  http://react-component.github.io/select/examples/getPopupContainer.html
