### ISSUE TITLE
Expand Tree Node when there is a match on the children of the Node

### ISSUE THREAD

**Issue by Marcoga** [react-component/tree-select#3]
**First of all**: Awesome work on the Component! Thanks!!

I want to show trees with deep hierarchies, which is why I want to set the ```treeDefaultExpandAll``` initially to false. However when I perform a search, and there are matches I would like to show the tree expanded. Is there a way to do this?

My first intuition was to set the ```treeDefaultExpandAll``` to true while doing a search:
```javascript
 <TreeSelect
    treeDefaultExpandAll={this.state.expandAll}
    onSearch={(val) => {
     this.setState({expandAll: (val && val !== '')})
    }}>
    ...
/>
```

But my aproach does not work, the tree does not expand while typing. Is there a way to do this. I would also be willing to help out in any way.

**Comment by warmhug** [comment]
the props begin with `default` generally are uncontrolled (ref: http://facebook.github.io/react/docs/forms.html#default-value)

Should add new feature to meet it.

**Comment by warmhug** [comment]
Try latest version
