### ISSUE TITLE
Search performance issue

### ISSUE THREAD

**Issue by dotSlashLu** [react-component/tree-select#31]
We are loading a tree of thousands of leaves, this component shows it perfectly, but it's so slow to search that it blocks the whole web page for a long while with high CPU usage. 

Searching through this amount of leaves wasn't a issue with the jQuery fancytree we used before, so I guess the issue isn't with react, maybe we can figure out a way to improve the search method?

**Comment by warmhug** [comment]
Now, I change search check mode to use `treeCheckStrictly` auto. Search performance should improve. Try rc-tree-select@1.7.9

#21

**Comment by dotSlashLu** [comment]
It's a huge improvement! Thanks!
