### ISSUE TITLE
the disabled data doesn't refresh 

### ISSUE THREAD

**Issue by ccoat2** [react-component/tree-select#33]
I cannot change the disabled data, when I change the treeData it doesn't render as the treeData is. The component seems to don't change his property.

**Comment by warmhug** [comment]
try `treeDate = Object.assign({}, treeData)`

**Comment by ccoat2** [comment]
it doesn't work :(
I get the same problem it's very strange because everything works fine except this ...

**Comment by warmhug** [comment]
It works fine, see here http://react-component.github.io/tree-select/examples/filter.html
![image](https://cloud.githubusercontent.com/assets/2011119/17916529/b459cb20-69e6-11e6-889d-ac9a7bf80b7d.png)

**Comment by Lilion12** [comment]
Hello @warmhug,

I'm having the same problem as @ccoat2 : 

Using this code : 
`import 'rc-tree-select/assets/index.css';
import React from 'react';
import TreeSelect, {SHOW_PARENT} from 'rc-tree-select';


class SelectTree extends React.Component {

  mapData(allPays, parentId, selectedStore) {
    var returnData = [];
    allPays.forEach(pays => {
      returnData.push(
        {
          pId: parentId,
          key: pays.typeNumTiers + pays.numTiers,
          value:  pays.numTiers,
          label: pays.label,
          disabled : pays.numTiers == selectedStore
        });
        returnData = returnData.concat(this.mapData(pays.children, pays.typeNumTiers + pays.numTiers,selectedStore));
    });
    return returnData;
  }

  render() {

    if (this.props.treeData === undefined) {
      return (<div></div>);
    }
    console.log( this.props.selectedStore);
    const data = this.mapData(this.props.treeData, 0, this.props.selectedStore);
    console.log(data);
    return (
      <TreeSelect
        className="select_country"
        transitionName="rc-tree-select-dropdown-slide-up"
        choiceTransitionName="rc-tree-select-selection__choice-zoom"
        dropdownStyle={{height: 200, overflow: 'auto'}}
        dropdownPopupAlign={{overflow: {adjustY: 0, adjustX: 0}, offset: [0, 2]}}
        searchPlaceholder="Please choose a store"
        treeLine
        maxTagTextLength={15}
        treeNodeFilterProp="title"
        labelInValue={true}
        inputValue={null}
        showSearch={false}
        treeData={data}
        treeDataSimpleMode={{
          id: 'key',
          rootPId : 0
        }}
        defaultValue={this.props.defaultValue}
        onChange={this.props.onChange}
        multiple={this.props.multiple}
        allowClear={this.props.allowClear}
        treeCheckable={this.props.treeCheckable}
      />
    );
  }
}
module.exports = SelectTree;
`

Using the simple mode with this data 
![image](https://cloud.githubusercontent.com/assets/5870982/18011452/94bf9daa-6bb5-11e6-8cd9-0174ce23ad97.png)

We change the selected store in another component then the TreeSelect should rerender and update with this data 

![image](https://cloud.githubusercontent.com/assets/5870982/18011441/81a7fd7a-6bb5-11e6-92df-d9f3398edbdc.png)

However, it keeps the old data even after rendering, as depicted.

![image](https://cloud.githubusercontent.com/assets/5870982/18011500/c0b247be-6bb5-11e6-9cbd-784176fa9605.png)

Can you help us on this topic? 

Cheers !

**Comment by warmhug** [comment]
@Lilion12  @ccoat2 thanks.
