### ISSUE TITLE
Disabled nodes cannot be wrapped

### ISSUE THREAD

**Issue by clementdevos** [react-component/tree-select#35]
Hello, 

Could it be possible to add a feature to wrap the disabled nodes?

Cheers, 

Lilion12

**Comment by warmhug** [comment]
How to wrap it? Show your code?

**Comment by Lilion12** [comment]
We would like to disable the parent but leave the children nodes enabled.

**Comment by yesmeck** [comment]
Use TreeNode[disabled].
