### ISSUE TITLE
Icon prop for TreeNode

### ISSUE THREAD

**Issue by Marcoga** [react-component/tree-select#4]
I have trees which have icons; these icons depend on the current value of the node (level, node type), and gets the image from the Server. Something like this: ``` `./ImageLoader/${node.level}/${node.type}` ```. Right now I can embed the image on the title:

```javascript
<TreeNode
  title={
    <div>
      <img src={'myurl...'} />
      <span>{node.title}</span>
    </div>}
  value={node.value}
  key={node.key}
  isLeaf
/>
```

The problem with this aproach is that:
* I would not get the node title on the onSelect event
* The Image would also be visible when the tree is not open

Would you consider extending the API of the TreeNode to accept an icon prop? I could also prepare a PR if you would be willing to integrate it.

**Comment by warmhug** [comment]
Welcome your PR
