### ISSUE TITLE
treeDefaultExpanedKeys => treeDefaultExpandedKeys

### ISSUE THREAD

**Issue by afc163** [react-component/tree-select#45]
然后发个升级 PR 到 antd featrue 分支，并补充下文档。

https://github.com/ant-design/ant-design/issues/4608

**Comment by yesmeck** [comment]
代码里是对的。。

**Comment by afc163** [comment]
2.7.0 的 changelog 貌似错了。

https://github.com/ant-design/ant-design/blob/master/CHANGELOG.zh-CN.md#270
