### ISSUE TITLE
treeCheckStrictly， treeCheckable两属性都为true时，报错

### ISSUE THREAD

**Issue by mosikoo** [react-component/tree-select#46]
treeCheckStrictly， treeCheckable两属性都为true时，rc-animate会报错

错误显示

Animate.js:290 Uncaught Error: must set key for <rc-animate> children at http://localhost:3000/dist/demo.js:2646:18 at Array.map (native) at Constructor.render (http://localhost:3000/dist/demo.js:2641:33) at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/node_modules/react/dist/react-with-addons.js:6336:34) at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/node_modules/react/dist/react-with-addons.js:6356:32) at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (http://localhost:3000/node_modules/react/dist/react-with-addons.js:12883:21) at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/node_modules/react/dist/react-with-addons.js:5969:30) at ReactCompositeComponentWrapper.wrapper [as mountComponent] (http://localhost:3000/node_modules/react/dist/react-with-addons.js:12883:21) at Object.mountComponent (http://localhost:3000/node_modules/react/dist/react-with-addons.js:13617:35) at ReactDOMComponent.mountChildren (http://localhost:3000/node_modules/react/dist/react-with-addons.js:12222:44)

**Comment by yesmeck** [comment]
Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by mosikoo** [comment]
demo在这： http://codepen.io/mosikoo/pen/OWoBVr?editors=0011

treeCheckStrictly， treeCheckable 一起存在报错

**Comment by myqianlan** [comment]
两者存在 然后赋默认值的时候会报错

**Comment by yesmeck** [comment]
`treeCheckStrictly` 和 `treeCheckable` 同时为 `ture` 的是时候， `labelInValue` 会变成 `true`，`value` 要写成 `{ value: '0-0-1-value', label: '0-0-1-label' }` 的形式。
