### ISSUE TITLE
treeCheckable模式下。在输入框按下BACKSPACE删除时不能正确删除节点

### ISSUE THREAD

**Issue by mosikoo** [react-component/tree-select#47]
treeCheckable模式下， 页面刚刚进入，按下BACKSPACE键在inputValue为空的情况下首次能删除node节点。  删除后再选中节点， 再按下BACKSPACE键，发现节点不能删除。

demo：http://codepen.io/mosikoo/pen/RKYeJv?editors=0110

出现bug处： https://github.com/react-component/tree-select/blob/master/src/Select.jsx#L321-L324

我觉得在this.fireChange(value);前上
```
this. _checkedNodes =  xxxx  // 这里xxx指value值
```

**Comment by yesmeck** [comment]
Fixed in 1.9.2
