### ISSUE TITLE
TabIndex support

### ISSUE THREAD

**Issue by Sandster** [react-component/tree-select#48]
Hello,

would be great to add support for tabIndex. So tree-select can be accessed via tab and open the option list by space bar?

Thank you
Sandster

**Comment by paranoidjk** [comment]
PR is welcome.

**Comment by yesmeck** [comment]
@warmhug 还记得为什么 multiple 不设置 tabIndex 吗？ https://github.com/react-component/tree-select/blob/master/src/Select.jsx#L868-L873

**Comment by warmhug** [comment]
记得多选或 combobox 下 都有 input 框，焦点应该直接定位在 input 框内。
