### ISSUE TITLE
Custom template for dropdown items

### ISSUE THREAD

**Issue by mrchief** [react-component/tree-select#56]
Is it possible to pass custom templates for drowdown items? For example, adding info icons and exclude buttons.

![untitled](https://cloud.githubusercontent.com/assets/781818/24472999/cfeff350-1495-11e7-8dad-4f47f3ddeb73.jpg)

I also tried to add custom styles to items (like greying out certain items) but that didn't work.

Is there any way to do these?

**Comment by yesmeck** [comment]
You can pass ReactNode to TreeNode[title].
