### ISSUE TITLE
Search case insensitive 

### ISSUE THREAD

**Issue by jlevesque** [react-component/tree-select#59]
It seems that the current version does not have a insensitive string compare. Will it be possible to make the search case insensitive.

We can add a props that will trigger the type of search.

If I'm not wrong, it may there where we will need to change the current behviour :

SelectTrigger.jsx line 265 to 273
```
loopAllChildren(treeNodes, (child) => {
      if (props.value.some(item => item.value === getValuePropValue(child))) {
        keys.push(child.key);
      }
      if (props.halfCheckedValues &&
        props.halfCheckedValues.some(item => item.value === getValuePropValue(child))) {
        halfCheckedKeys.push(child.key);
      }
    }); 
```

**Comment by yesmeck** [comment]
Use `filterTreeNode` to create your own filter function.

**Comment by jlevesque** [comment]
Thanks, I didn't saw it in the docs.
