### ISSUE TITLE
选择器搜索问题

### ISSUE THREAD

**Issue by linhanyang** [react-component/tree-select#63]
你好。
操作步骤：
1、搜索关键字遍历：b10
2、清除搜索
3、点开 a ， disabled中的a12无法展开
![image](https://user-images.githubusercontent.com/7603016/28314311-99add664-6bec-11e7-9525-bdb4ba6c6dd8.png)

请问这种情况如何处理？
谢谢

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/6886
