### ISSUE TITLE
how to disable 'remove' selection?

### ISSUE THREAD

**Issue by plandem** [react-component/tree-select#9]
Is it possible to have 'single' selection, but to mark selected items? here is case:

1) user selected somewhere some items, each item has additional settings that has no any connection with 'tree'
2) user want to add a new item - popup with tree is opened and user must a new one selection.
3) user want to know what items he/she already selected, so we need somehow to mark already selected items (right now it's possible only with multiple mode)
4) multiple mode can't be used, because user must select one by one, because each selection has additional settings, so case is: user select option, configure it. select another one and configure it. but! during selection he must see somehow items that were already selected before.

**Comment by warmhug** [comment]
How about manually saving the already selected info on the single selection mode. Like this example, http://react-component.github.io/tree/examples/basic.html

![image](https://cloud.githubusercontent.com/assets/2011119/13165341/7dea1ae0-d6f7-11e5-904c-9bf13b5e8053.png)

**Comment by plandem** [comment]
but that's for 'tree' not 'tree-select'. I can't find any 'defaultSelectedKeys' at documentation for the tree-select :(

**Comment by warmhug** [comment]
It's `value / defaultValue` api in tree-select.

**Comment by plandem** [comment]
i see. looks like docs for tree-select is outdated :) thanks anyway!
