### ISSUE TITLE
How can I delete and re-render.

### ISSUE THREAD

**Issue by surinder-sammy** [react-component/tree-select#91]
Actually my requirement is I want to set the nodes checked via options (api). I have autocomplete input with same data when user choose the value from that input i want to set same node checked in this tree.

**Comment by yesmeck** [comment]
Use `value` to control which nodes to check.

**Comment by surinder-sammy** [comment]
How can change values after rendered?

**Comment by yesmeck** [comment]
See https://reactjs.org/docs/forms.html#controlled-components
