### ISSUE TITLE
treeDataSimpleMode 选项的意义?

### ISSUE THREAD

**Issue by MwumLi** [react-component/tree-select#92]
看了文档和示例以及一些issue，不是太懂这个选项的意义
然后看了源码 [export function processSimpleTreeData](https://github.com/react-component/tree-select/blob/master/src/util.js#L509-L529), **才发现仅仅是做了应对treeData数据中 key 不是 id 的情况, 并且不破坏原有数据**
所以, treeDataSimpleMode 选项的意义是我理解的这样吗?

**Comment by yesmeck** [comment]
还处理了父子关系。

**Comment by MwumLi** [comment]
@yesmeck 你所说的处理父子关系, 是指 [export function processSimpleTreeData](https://github.com/react-component/tree-select/blob/master/src/util.js#L509-L529) 里面的 [parent.children = children;](https://github.com/react-component/tree-select/blob/master/src/util.js#L521)吗?

**Comment by yesmeck** [comment]
对。

**Comment by MwumLi** [comment]
那么我觉得这个 `treeDataSimpleMode` 这个选项表达的设计意图就不是那么清楚了,父子关系处理完全是 [export function processSimpleTreeData](https://github.com/react-component/tree-select/blob/master/src/util.js#L509-L529) 这个函数做的, 而不是 `treeDataSimpleMode` 所表达的设计意图, 所以 `treeDataSimpleMode` 仅仅只是做到了指定 key 的键的用处, 如果是我, 我可能仅仅会指定一个 props 来明确指定这个 key 值, 类似组件里 `treeNodeFilterProp` 这个选项一样, 目的明确, 用法简单 

我不知道你们之后是否会对于这个选项做更多的考虑, 比如考虑到大量数据下, 为了性能优化, 只保留 `treeDataSimpleMode` 中的指定的数据项.

**Comment by yesmeck** [comment]
😳 这个属性 `treeDataSimpleMode` 只是说你可以传非树状结构的数据给组件。跟性能什么的没有关系。。。当然树组件非常需要性能上的优化，如果你有兴趣，欢迎一起来看看怎么来做优化比较好。
